# Service do tipo ClusterIP para comunicação INTERNA
# URL: http://mss-ingredient-classifier-service:8000
apiVersion: v1
kind: Service
metadata:
  name: mss-ingredient-classifier-service
  labels:
    app: mss-ingredient-classifier
spec:
  selector:
    app: mss-ingredient-classifier
  ports:
    - name: http-classifier
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # Acessível apenas dentro do cluster