# Service do tipo ClusterIP para comunicação INTERNA com o MSS Profile Service
# URL interna: http://mss-profile-service-service:5000
apiVersion: v1
kind: Service
metadata:
  name: mss-profile-service-service
  labels:
    app: mss-profile-service
spec:
  selector:
    app: mss-profile-service
  ports:
    - name: http-profile
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP