# Service do tipo ClusterIP para comunicação INTERNA com o MSS Profile Dart
# URL interna no K8s: http://mss-profile-service-dart-service:5000
# Caminho: back/kubernetes/services/mss-profile-service-dart-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mss-profile-service-dart-service # Nome do Service para o DNS do K8s
  labels:
    app: mss-profile-service-dart
spec:
  selector:
    app: mss-profile-service-dart # Deve corresponder ao label no Deployment
  ports:
    - name: http-profile-dart
      protocol: TCP
      port: 5000       # Porta interna do Service
      targetPort: 5000 # Porta do contêiner (Dart app)
  type: ClusterIP