# Deployment para o Microsserviço de Perfil
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mss-profile-service-deployment
  labels:
    app: mss-profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mss-profile-service
  template:
    metadata:
      labels:
        app: mss-profile-service
    spec:
      containers:
      - name: mss-profile-service-container
        image: leoramadio/mss-profile-service:latest # Sua imagem no Docker Hub
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          # Variáveis de DB injetadas do Secret (cookster-auth-secrets)
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cookster-auth-secrets
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: cookster-auth-secrets
              key: DB_PASS
          # URL do Event Bus (Comunicação interna via Service Name do Kubernetes)
        - name: EVENT_BUS_URL
          value: "http://event-bus-service:4000"
        - name: SERVICE_PORT
          value: "5000"
        - name: SERVICE_URL
          value: "http://mss-profile-service-service"
        # O CMD do Dockerfile é usado automaticamente (node server.js)