name: mss_profile_service
description: MicroserviÃ§o de perfil reimplementado em Dart
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  mongo_dart: ^0.10.3
  http: ^1.2.2
  dotenv: ^4.2.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
