apiVersion: v1
kind: Secret
metadata:
  name: cookster-auth-secrets
type: Opaque
data:
  DB_USER: bGVvbmFyZG9hbWFkaW80
  DB_PASS: aktEOXBGWGEySmU3RTN0Rw==
  JWT_SECRET: REpWSkRWS0pEU0JGSVVFUktET0ZJT0RCTklVRUJSQCQhIUBHRktHTkROSkFORkpO
  GOOGLE_CLIENT_ID: ODE5OTkwMjI5MjIyLWhjaGRqaDMyYzEyYjZycWltYmtka2Nlc2V2bGUyOGpzLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_CLIENT_SECRET: R09DU1BYLXBXY2tqSFo0eXhQOGRjM2ltUGdLYkE3MjlqVnU=
  FACEBOOK_CLIENT_ID: Njk4NzY3MjI2MDE2NjEw
  FACEBOOK_CLIENT_SECRET: OWEzNWJiNjllZjgzYWI4NjgwMmJjNzNlN2U2Njg1MjM=