apiVersion: v1
kind: Secret
metadata:
  name: cookster-auth-secrets
type: Opaque
data:
  # DB_USER=leonardoamadio4 -> base64
  DB_USER: bGVvbmFyZG9hbWFkaW80
  # DB_PASS=m1azHugYEs3lRCuy -> base64
  DB_PASS: bTFhekh1Z1lFczNsUkN1eQ==
  # JWT_SECRET=DJVJDVKJDSBFIUERKDOFIODBNIUEBR@$!!@GFKGNDNJANFJN -> base64
  JWT_SECRET: RUpWSkVESktKRFNCVklVRVJLRE9GSU9EQk5JVUVCUkAkISEhQEdGS0dORE5KQU5GSk4=
  # GOOGLE_CLIENT_ID=... -> base64
  GOOGLE_CLIENT_ID: ODE5OTkwMjI5MjIyLWhjaGRqaDMyYzEyYjZxcmlybWJpZGRrY2VzZXZsZTI4anMuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20=
  # GOOGLE_CLIENT_SECRET=... -> base64
  GOOGLE_CLIENT_SECRET: R09DU1BYLXBXQ2tISFo0eXhQOGRjM2ltUGdLYkE3MjlqVnU=
  # FACEBOOK_CLIENT_ID=... -> base64
  FACEBOOK_CLIENT_ID: Njk4NzY3MjI2MDE2NjEw
  # FACEBOOK_CLIENT_SECRET=... -> base64
  FACEBOOK_CLIENT_SECRET: OWEzNWJiNjllZjgzYWI4NjgwMmJjNzNlN2U2Njg1MjM=